export const CHECK_EMAIL = 'CHECK_EMAIL'
export const CHECK_VERIFICATION = 'CHECK_VERIFICATION'
export const RESET_PASSWORD = 'RESET_PASSWORD'
export const RESET_SUCCESS = 'RESET_SUCCESS'

export const STEP_BUTTON_CONTENT = {
  [CHECK_EMAIL]: '取得驗證碼',
  [CHECK_VERIFICATION]: '提交驗證碼',
  [RESET_PASSWORD]: '重設密碼',
  [RESET_SUCCESS]: '返回登入',
}
