export const CMD_CODE = {
  // ACTION
  WEB_SOCKET_LOGIN_REQUEST: '00',
  WEB_SOCKET_LOGIN_RESPONSE: '01',

  GET_CHANNEL_HISTORY_REQUEST: '40',
  GET_CHANNEL_HISTORY_RESPONSE: '41',

  SEND_CHAT_MESSAGE_REQUEST: '10',
  SEND_CHAT_MESSAGE_RESPONSE: '11',
  // BC
  CHAT_MESSAGE_NOTIFY: '20',
  USER_LOGIN_NOTIFY: '30',
  USER_LOGOUT_NOTIFY: '31',
  USER_LIKES_POST: '50',
  USER_COMMENT_POST: '60',
}

export const ERROR = {}
